--- 
- 
  become: true
  hosts: pj_node_VMs
  tasks: 
    - 
      name: "install Apache server"
      yum: 
        name: httpd
        state: latest
    - 
      name: "enable and start Apache server"
      service: 
        enabled: true
        name: httpd
        state: started
    - 
      firewalld: 
        immediate: true
        permanent: true
        service: http
        state: enabled
      name: "open firewall port"
    - 
      group: 
        name: web
        state: present
      name: "create web admin group"
    - 
      name: "create web admin user"
      user: 
        append: true
        comment: "Web Admin"
        groups: web
        name: webadm
        password: $6$eFpYXH3Ezgb1wd0T$s1aPhxbeB/tbPNk1t8T5rsPQWZHoL.6lvYN5IOaLchWFPwqkAIxqHKQ.sz0CI41VmLS.TWF3.SYpZAVmcWsWw1
    - 
      file: 
        group: web
        mode: "u=rwx,g=rwx,o=rx,g+s"
        owner: root
        path: /var/www/html
        state: directory
      name: "set content directory group/permissions"
    - 
      copy: 
        content: "Welcome to {{ ansible_fqdn}} on {{ ansible_default_ipv4.address }}"
        dest: /var/www/html/index.html
        group: web
        mode: "u=rw,g=rw,o=r"
        owner: webadm
      name: "create default page content"

